<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net9.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>Ams2.ControlCenter</RootNamespace>
    <AssemblyName>Ams2.ControlCenter</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Ams2.Shared\Ams2.Shared.csproj" />
  </ItemGroup>
</Project>
