<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net9.0-windows</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <Platforms>x64</Platforms>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Vortice.Win32.Graphics.Direct3D11" Version="2.5.0" />
    <PackageReference Include="Vortice.Win32.Graphics.Dxgi" Version="2.5.0" />
    <PackageReference Include="Vortice.Win32.Graphics.Direct2D" Version="2.5.0" />
    <PackageReference Include="Vortice.Win32.Graphics.DirectWrite" Version="2.5.0" />
    <PackageReference Include="Vortice.Win32.Graphics.DirectComposition" Version="2.5.0" />
  </ItemGroup>

</Project>
